Repository mattermost/mattermost-api-reference, pull requests merged in 2018-04, with the labels that each got.

#354 Clarify what deleting a channel or team do
  v4/source/channels.yaml
  v4/source/teams.yaml
Labels: For Existing API

#357 [GH-7775] Add docs for /channels/{channel_id}/convert
  v4/source/channels.yaml
Labels: 3: Code Merged

#359 Update description for GET /plugins/webapp
  v4/source/plugins.yaml
Labels: For Existing API

#362 [MM-10354] Add APIv4 to remove team icon
  v4/source/teams.yaml
Labels: 2: Proposal Accepted
