Repository mattermost/mattermost-api-reference, pull requests merged in 2018-11, with the labels that each got.

#388 MM-11725: Adding new search_autocomplete channels api
  v4/source/channels.yaml
Labels: 2: Proposal Accepted

#387 add channeltimezone api
  v4/source/channels.yaml
  v4/source/definitions.yaml
Labels: 3: Code Merged

#402 Added API docs for GetUserTermsOfService API
  v4/source/definitions.yaml
  v4/source/users.yaml
Labels: 3: Code Merged

#395 Adding the set default profile image endpoint
  v4/source/users.yaml
Labels: 2: Proposal Accepted

#389 Add auth_data and auth_service fields to POST /users API call
  v4/source/users.yaml
Labels: For Existing API

#375 /users/stats api endpoint documentation.
  v4/source/definitions.yaml
  v4/source/users.yaml
Labels: 2: Proposal Accepted, 3: Code Merged
