Repository mattermost/mattermost-api-reference, pull requests merged in 2018-10, with the labels that each got.

#399 Add documentation for 'include_deleted' pt2
  v4/source/channels.yaml
Labels: 1: Proposal Review

#398 Add documentation for "include_deleted" parameter
  v4/source/channels.yaml
Labels: 1: Proposal Review

#396 Fix attahment --> attachment typo
  v4/source/definitions.yaml
Labels: For Existing API

#394 #UTCINT-110 added api doc for register user service terms action
  v4/source/definitions.yaml
  v4/source/service_terms.yaml
  v4/source/users.yaml
Labels: 3: Code Merged

#383 A new file return a status code 201 if success
  v4/source/files.yaml
Labels: For Existing API

#401 Add documentation for the delete brand image action
  v4/source/brand.yaml
Labels: 3: Code Merged
