Repository mattermost/mattermost-api-reference, pull requests merged in 2018-06, with the labels that each got.

#376 Adds link to WIP Postman documentation.
  v4/source/introduction.yaml
Labels: 2: Proposal Accepted

#377 MM-10928: fix /system/ping docs
  v4/source/system.yaml
Labels: For Existing API

#374 MM-6992 Added "matches" field to post search results
  v4/source/definitions.yaml
  v4/source/posts.yaml
Labels: 1: Proposal Review

#371 Remove extra_update_at from Channels call
  v4/source/definitions.yaml
Labels: For Existing API

#372 Docs for v5.0
  v4/source/introduction.yaml
Labels: For Existing API

#379 Fix opengraph endpoints being excluded
  Makefile
Labels: For Existing API
