Repository mattermost/mattermost-api-reference, pull requests merged in 2018-05, with the labels that each got.

#339 MM-8799: Basic Schemes API
  Makefile
  v4/source/definitions.yaml
  v4/source/introduction.yaml
  v4/source/schemes.yaml
Labels: 2: Proposal Accepted

#360 MM-10182: Adds docs for update team scheme endpoint.
  v4/source/teams.yaml
Labels: 1: Proposal Review

#364 Fixing api reference build problem
  v4/source/teams.yaml
Labels: 2: Proposal Accepted

#349 MM-9779: Add api documentation changes for avoid re-join on invitations feature
  v4/source/teams.yaml
  v4/source/users.yaml
Labels: 1: Proposal Review

#365 [MM-10433] Update permission of converting a channel from public to private to allow team admin
  v4/source/channels.yaml
Labels: 2: Proposal Accepted

#366 Fix invitation token id query parameter name
  v4/source/users.yaml
Labels: For Existing API

#358 Update API deprecation notice based on user feedback
  v4/source/introduction.yaml
Labels: For Existing API

#367 Add permissions to get endpoint and increase versions to 5.0
  v4/source/schemes.yaml
  v4/source/teams.yaml
Labels: For Existing API

#368 MM-10605 Add int64 format to timestamps
  v4/source/definitions.yaml
Labels: For Existing API

#370 Add descriptions for timestamp fields
  v3/source/definitions.yaml
  v4/source/definitions.yaml
Labels: For Existing API

#369 MM-9916 Add note about permanent delete for teams
  v4/source/teams.yaml
Labels: For Existing API

#361 MM-10183: Adds docs for update channel scheme endpoint.
  v4/source/channels.yaml
Labels: 3: Code Merged

#352 MM-9730: API to manage the scheme props of team members.
  v4/source/teams.yaml
Labels: 3: Code Merged

#355 MM-9729: Update scheme roles endpoint for Channel Members.
  v4/source/channels.yaml
Labels: 3: Code Merged
