Repository mattermost/mattermost-api-reference, pull requests merged in 2018-03, with the labels that each got.

#336 PLT-8186 add documentation
  v4/source/system.yaml
Labels: 3: Code Merged

#334 PLT-7567: Integration of Team Icons
  v4/source/teams.yaml
Labels: 3: Code Merged

#338 Fix "users/status/ids" API documentation
  v4/source/status.yaml
Labels: For Existing API

#337 MM-8604: document `config_changed` and `license_changed`
  v4/source/introduction.yaml
Labels: 2: Proposal Accepted

#342 update doc for testEmail
  v4/source/system.yaml
Labels: 3: Code Merged

#343 update s3 test doc
  v4/source/system.yaml
Labels: 2: Proposal Accepted

#341 [MM-9798] API v4 Documentation for Status/Get User Status does not match payload received
  v4/source/definitions.yaml
Labels: For Existing API

#346 Update team icon API description
  v4/source/teams.yaml
Labels: 3: Code Merged
