Repository mattermost/mattermost-api-reference, pull requests merged in 2019-06, with the labels that each got.

#450 Add missing parameters section to Get Open Graph Metadata API
  v4/source/opengraph.yaml
Labels: 3: Code Merged

#453 MM-16067 Docs for bot APIs
  Makefile
  v4/source/bots.yaml
  v4/source/definitions.yaml
  v4/source/introduction.yaml
Labels: For Existing API

#445 [MM-13500] Add /group/search and /users/group_channels endpoint docs
  v4/source/channels.yaml
  v4/source/users.yaml
Labels: 2: Proposal Accepted, APIv4
