Repository mattermost/mattermost-api-reference, pull requests merged in 2019-07, with the labels that each got.

#458 MM-15452 - Add docs for /bots/{bot_user_id}/icon
  Makefile
  README.md
  v4/source/bots.yaml
  v4/source/introduction.yaml
Labels: 1: Proposal Review, APIv4

#460 Update introduction.yaml
  v4/source/introduction.yaml
Labels: 3: Code Merged

#457 MM-16477 Add since parameter to /api/v4/users/ids
  v4/source/users.yaml
Labels: 3: Code Merged, Do Not Merge/Awaiting Next Release, Lifecycle/frozen

#461 [MM-17194] Document the case for channel search where the user don't have the list_team_channels permission
  v4/source/channels.yaml
Labels: 3: Code Merged

#462 add circleci
  .circleci/config.yml
  build/Jenkinsfile.master
  build/Jenkinsfile.pr
Labels: 2: Proposal Accepted

#463 MM-17412 Remove file_ids from update post API
  v4/source/posts.yaml
Labels: 3: Code Merged
