Repository mattermost/mattermost-api-reference, pull requests merged in 2019-10, with the labels that each got.

#474 [MM-17754] add post_unread event to websocket
  v4/source/introduction.yaml
Labels: 3: Code Merged

#472 Fix failing go code in user API samples
  v4/source/users.yaml
Labels: 1: Proposal Review, Lifecycle/1:stale

#476 Adds the "link" type to the embed definition
  v4/source/definitions.yaml
Labels: 1: Proposal Review, 3: Code Merged, For Existing API

#470 MM-15219 Add support for introduction text in interactive dialogs
  v4/source/actions.yaml
Labels: 2: Proposal Accepted

#477 Adding guest related endpoints to the documentation
  v4/source/teams.yaml
  v4/source/users.yaml
Labels: 2: Proposal Accepted

#479 fix websocket authentication wording
  v4/source/introduction.yaml
Labels: 2: Proposal Accepted, Hacktoberfest

#478 [MM-13155] Finished documentation for the group endpoints
  v4/source/definitions.yaml
  v4/source/groups.yaml
Labels: 2: Proposal Accepted
