Repository mattermost/mattermost-api-reference, pull requests merged in 2019-02, with the labels that each got.

#418 Fix a typo and broken links
  CONTRIBUTING.md
  v4/source/roles.yaml
Labels: For Existing API, Hackfest

#419 Documentation update
  v4/source/users.yaml
Labels: For Existing API

#421 Update posts.yaml
  v4/source/posts.yaml
Labels: For Existing API

#425 Add missing sections
  v4/source/introduction.yaml
  v4/source/opengraph.yaml
Labels: For Existing API, Hackfest

#426 [MM-13810] Adds user_id and team id required body parameters to the update endpoints
  v4/source/status.yaml
  v4/source/teams.yaml
Labels: 2: Proposal Accepted, APIv4, For Existing API

#420 Fix get a public file link response body correctly
  v4/source/files.yaml
Labels: For Existing API, Hackfest

#427 Add missing properties in PluginManifest
  v4/source/definitions.yaml
Labels: For Existing API, Hackfest

#428 Fix JavaScript WebSocket driver link to point mattermost-redux
  v4/source/introduction.yaml
Labels: For Existing API, Hackfest
