Repository mattermost/mattermost-api-reference, pull requests merged in 2019-05, with the labels that each got.

#441 [MM-8737] Add Go code samples to API reference for user endpoints
  v4/source/users.yaml
Labels: 2: Proposal Accepted

#440 [MM-15106] Add Go code samples to API reference for file endpoints
  v4/source/files.yaml
Labels: 2: Proposal Accepted

#438 [MM-15104] Add Go code samples to API reference for team endpoints
  v4/source/teams.yaml
Labels: 2: Proposal Accepted

#437 [MM-14751] Add group_constrained to the user list and search endpoints
  v4/source/users.yaml
Labels: 1: Proposal Review, APIv4

#447 Update Direct-channel API definition
  v4/source/channels.yaml
Labels: 1: Proposal Review
