Repository mattermost/mattermost-api-reference, pull requests merged in 2019-11, with the labels that each got.

#488 [MM-20015] Fix validation errors
  v4/source/brand.yaml
  v4/source/posts.yaml
  v4/source/system.yaml
Labels: 3: Code Merged

#486 [MM-19778] Update groups documentation to match changes for GET /groups
  v4/source/groups.yaml
Labels: 3: Code Merged

#487 Get channel members = channel memberships and roles
  v4/source/channels.yaml
Labels: 1: Proposal Review

#484 Adds docs for channel search.
  v4/source/channels.yaml
  v4/source/teams.yaml
Labels: 2: Proposal Accepted
