Repository mattermost/mattermost-api-reference, pull requests merged in 2019-04, with the labels that each got.

#433 Add documentation for get groups by channel and teams endpoints
  Makefile
  v4/source/definitions.yaml
  v4/source/groups.yaml
  v4/source/introduction.yaml
Labels: 1: Proposal Review, APIv4

#434 Fix plugin route
  v4/source/plugins.yaml
Labels: 3: Code Merged, For Existing API

#436 Remove deprecated LogSettings.FileFormat from config definition
  v4/source/definitions.yaml
Labels: 3: Code Merged

#435 MM-14748: Adding documentation for the new endpoint for revoke email invites
  v4/source/teams.yaml
Labels: 1: Proposal Review

#432 Updated API docs to include TOS fields being included in certain user APIs
  v4/source/definitions.yaml
  v4/source/users.yaml
Labels: 3: Code Merged, For Existing API

#423 MM-14294: update API to reflect hard-coded SAML certificate names
  v4/source/saml.yaml
Labels: 2: Proposal Accepted, For Existing API

#439 [MM-15105] Add Go code samples to API reference for plugin endpoints
  v4/source/plugins.yaml
Labels: 3: Code Merged
