Repository mattermost/mattermost-api-reference, pull requests merged in 2019-08, with the labels that each got.

#459 MM-11210 Add docs for GET '/users/{user_id}/channels/{channel_id}/posts/unread'
  v4/source/definitions.yaml
  v4/source/posts.yaml
Labels: 2: Proposal Accepted

#452 Adds docs for new endpoints.
  package-lock.json
  v4/source/channels.yaml
  v4/source/teams.yaml
Labels: 3: Code Merged, Lifecycle/1:stale

#466 [MM-7854] revoke sessions from all users
  v4/source/users.yaml
Labels: 3: Code Merged

#456 API docs for installing a plugin with a given url
  v4/source/plugins.yaml
Labels: 3: Code Merged

#465 Adds include_total_count query param.
  v4/source/teams.yaml
Labels: 3: Code Merged
