Repository mattermost/mattermost-api-reference, pull requests merged in 2020-06, with the labels that each got.

#527 MM-24425: Fix remaining references to non-v5 module
  package-lock.json
  v4/source/commands.yaml
  v4/source/users.yaml
Labels: 3: QA Review

#524 Adding trial license endpoint
  v4/source/system.yaml
Labels: 4: Reviews Complete

#529 MM-25293: Document that since is mutually exclusive from other params
  v4/source/posts.yaml
Labels: 2: Dev Review

#516 [MM-23719] Add move channel documentation
  v4/source/channels.yaml
Labels: 4: Reviews Complete

#528 [MM-25263] Add group stats endpoint
  v4/source/groups.yaml
  v4/source/users.yaml
Labels: 4: Reviews Complete

#531 MM-25261: get channels endpoint.
  v4/source/channels.yaml
Labels: 2: Dev Review

#533 [MM-21464] channels/move: reflect changes in the api
  v4/source/channels.yaml
Labels: 2: Dev Review

#535 [MM-25648] bots/users: add docs for conversions
  v4/source/bots.yaml
  v4/source/users.yaml
Labels: 4: Reviews Complete

#534 [MM-25646] Adds documentation for the permanent delete all users local endpoint
  v4/source/users.yaml
Labels: 4: Reviews Complete
