Repository mattermost/mattermost-api-reference, pull requests merged in 2020-01, with the labels that each got.

#492 Doc for operations over non existent plugins
  v4/source/plugins.yaml
Labels: 1: Proposal Review

#490 updated '/teams/{team_id}/members/batch'
  v4/source/teams.yaml
Labels: 2: Proposal Accepted

#493 [MM-19720] Add documentation for config patch endpoint
  v4/source/system.yaml
Labels: 2: Proposal Accepted, Lifecycle/frozen

#496 MM-19250 - documentation for new endpoint to retrieve command by id
  v4/source/commands.yaml
Labels: 2: Proposal Accepted

#489 MM-8607 - document serverbusy endpoints
  v4/source/definitions.yaml
  v4/source/system.yaml
Labels: 3: Code Merged

#497 Update link to JavaScript Driver
  v4/source/introduction.yaml
Labels: 3: Code Merged
