Repository mattermost/mattermost-api-reference, pull requests merged in 2020-04, with the labels that each got.

#504 Add php samples for users documentation
  v4/source/users.yaml
Labels: 2: Dev Review

#508 Add php samples for bots documentation
  v4/source/bots.yaml
Labels: 2: Dev Review

#509 MM-23015: Add OpenAPI changes for group mentions Phase 1
  v4/source/definitions.yaml
  v4/source/groups.yaml
Labels: 2: Dev Review, 2: QA Review

#510 [MM-23264] Add documentation for channel member counts by group
  v4/source/channels.yaml
  v4/source/definitions.yaml
Labels: 3: Reviews Complete

#512 API docs for RestoreTeam
  v4/source/teams.yaml
Labels: 3: Reviews Complete

#513 Adding GetKnownUsers api endpoint documentation
  v4/source/users.yaml
Labels: 3: Reviews Complete
