Repository mattermost/mattermost-api-reference, pull requests merged in 2020-09, with the labels that each got.

#570 MM-27352: Add doc for ldap certificate update/delete
  v4/source/ldap.yaml
Labels: 3: QA Review

#566 [MM-26812] Add documentation for new upload API endpoints
  Makefile
  v4/source/definitions.yaml
  v4/source/introduction.yaml
  v4/source/uploads.yaml
  v4/source/users.yaml
Labels: 4: Reviews Complete

#573 [MM-28580] Update docs for resumable uploads API endpoint
  v4/source/uploads.yaml
Labels: 4: Reviews Complete

#574 MM-28733: Add AdminAdvisor v2 new API method reference
  v4/source/system.yaml
Labels: 2: Dev Review, 3: QA Review

#577 MM-27147 - Added entry for Cloud api
  Makefile
  v4/source/cloud.yaml
  v4/source/definitions.yaml
  v4/source/introduction.yaml
Labels: 2: Dev Review

#579 [MM-28211] Added GetSubscription endpoint
  v4/source/cloud.yaml
  v4/source/definitions.yaml
Labels: 4: Reviews Complete
