Repository mattermost/mattermost-api-reference, pull requests merged in 2021-02, with the labels that each got.

#599 [MM-31790] Support Packet Generation DOCUMENTATION
  v4/source/system.yaml
Labels: 4: Reviews Complete

#605 [MM-31497] - Add spec for cloud/subscription/stats
  v4/source/cloud.yaml
  v4/source/definitions.yaml
Labels: 2: Dev Review

#606 added GetThreadMentionsForUserPerChannel
  v4/source/users.yaml
Labels: 2: Dev Review

#608 Bump version for /exports endpoint
  v4/source/exports.yaml
Labels: 4: Reviews Complete

#607 [MM-32543] - Add spec for cloud/alert/admin
  v4/source/cloud.yaml
Labels: 2: Dev Review

#613 [MM-32691] - Send email when the users are not able to join a workspace
  v4/source/cloud.yaml
Labels: 4: Reviews Complete

#617 Adding api docs for the new file search api endpoint
  v4/source/definitions.yaml
  v4/source/files.yaml
Labels: 4: Reviews Complete, AutoMerge
