Repository mattermost/mattermost-api-reference, pull requests merged in 2021-05, with the labels that each got.

#625 Adding operationIds to API documentation
  v4/source/actions.yaml
  v4/source/bleve.yaml
  v4/source/bots.yaml
  v4/source/brand.yaml
  v4/source/channels.yaml
  v4/source/cloud.yaml
  v4/source/cluster.yaml
  v4/source/commands.yaml
  v4/source/compliance.yaml
  v4/source/dataretention.yaml
  v4/source/elasticsearch.yaml
  v4/source/emoji.yaml
  v4/source/exports.yaml
  v4/source/files.yaml
  v4/source/groups.yaml
  v4/source/imports.yaml
  v4/source/jobs.yaml
  v4/source/ldap.yaml
  v4/source/oauth.yaml
  v4/source/opengraph.yaml
  v4/source/permissions.yaml
  v4/source/plugins.yaml
  v4/source/posts.yaml
  v4/source/preferences.yaml
  v4/source/reactions.yaml
  v4/source/roles.yaml
  v4/source/saml.yaml
  v4/source/schemes.yaml
  v4/source/service_terms.yaml
  v4/source/sharedchannels.yaml
  v4/source/status.yaml
  v4/source/system.yaml
  v4/source/teams.yaml
  v4/source/uploads.yaml
  v4/source/users.yaml
  v4/source/webhooks.yaml
Labels: 2: Dev Review

#629 add dnd_end_time in requestBody of updateStatus
  v4/source/status.yaml
Labels: 2: Dev Review

#639 MM-35802 Rename json fields for GetAllSharedChannels to match other channel objects
  v4/source/definitions.yaml
Labels: 4: Reviews Complete

#641 Revert "add dnd_end_time in requestBody of updateStatus (#629)"
  v4/source/status.yaml
Labels: 4: Reviews Complete, AutoMerge
