Repository mattermost/mattermost-api-reference, pull requests merged in 2022-10, with the labels that each got.

#720 plugin-config-patch-update
  v4/source/system.yaml
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#688 [MM-42897] - Remove reference to removed cloud endpoints
  v4/source/cloud.yaml
Labels: 4: Reviews Complete

#719 Add Playbook APIs to Mattermost API docs
  .gitignore
  Makefile
  README.md
  package-lock.json
  package.json
  playbooks/extract.js
  playbooks/merge-definitions.js
  playbooks/merge-tags.js
  playbooks/tags.yaml
Labels: 2: Dev Review, Contributor

#721 Apply abandoned API documentation correction #5992
  v4/source/commands.yaml
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#722 fixing output GetKnownUsers to array
  v4/source/definitions.yaml
  v4/source/users.yaml
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor
