Repository mattermost/mattermost-api-reference, pull requests merged in 2022-06, with the labels that each got.

#700 [MM-42192] Documentation for getting deleted posts
  v4/source/posts.yaml
Labels: 4: Reviews Complete, Contributor

#701 Fix App Directory Link
  v4/source/introduction.yaml
Labels: 2: Dev Review, Contributor

#699 [MM-42194] Added documentation for new 'include_deleted' query param on get file info api
  v4/source/posts.yaml
Labels: 4: Reviews Complete, Contributor

#702 [MM-42792] Modified notify_props docs to include only strings, not booleans
  v4/source/definitions.yaml
Labels: 4: Reviews Complete, Contributor

#698 [MM-44434] Introduced new api docs for search endpoint variable include_search_b…
  v4/source/channels.yaml
Labels: Lifecycle/1:stale, 2: Dev Review, Contributor

#704 Mm-20223 Add webp emoji support
  v4/source/emoji.yaml
Labels: 4: Reviews Complete, Lifecycle/1:stale, Contributor
