Repository mattermost/mattermost-api-reference, pull requests merged in 2022-03, with the labels that each got.

#670 Add missing types to array definitions in channels and dataretention
  v4/source/channels.yaml
  v4/source/dataretention.yaml
Labels: 4: Reviews Complete, Contributor

#680 [MM-35572] Add missing params paramsGetPostsAroundLastUnread
  v4/source/posts.yaml
Labels: 2: Dev Review, Contributor

#678 Update ping to add push notification test definition
  v4/source/definitions.yaml
  v4/source/system.yaml
Labels: 4: Reviews Complete

#679 [MM-41981] Always install the latest compatible version via the Marketplace
  v4/source/plugins.yaml
Labels: 4: Reviews Complete

#674 MM-38164: Add documentation for the new params in GetPostThread
  v4/source/definitions.yaml
  v4/source/posts.yaml
Labels: 4: Reviews Complete

#652 Clarify how to change system configuration
  v4/source/system.yaml
Labels: 4: Reviews Complete

#683 Replaced http URLs with https in various places
  README.md
  v4/source/introduction.yaml
Labels: 4: Reviews Complete

#686 update GetEmojiList's per_page to refer to emojis
  v4/source/emoji.yaml
Labels: 2: Dev Review, Contributor
