Repository mattermost/mattermost-api-reference, pull requests merged in 2022-02, with the labels that each got.

#671 MM-41184: Remove the config migrate endpoint
  v4/source/system.yaml
Labels: 4: Reviews Complete

#673 Add a note on binary websocket messages
  v4/source/introduction.yaml
Labels: 4: Reviews Complete

#664 Added docs for 4 new endpoints related to custom groups.
  v4/source/groups.yaml
Labels: 2: Dev Review

#677 Updated channel endpoint parameters
  v4/source/channels.yaml
Labels: 4: Reviews Complete

#676 [MM-41679] Adding missing parameters
  v4/source/groups.yaml
  v4/source/teams.yaml
  v4/source/users.yaml
Labels: 4: Reviews Complete, Contributor
